// --- Definitions of block type, orientation and font texture ---

export const blockDefinitions = [
    { "name": "[00] Blank", "isOriented": false, "isTextured": false },
    { "name": "[01] Stone", "isOriented": false, "isTextured": false },
    { "name": "[02] Brick", "isOriented": false, "isTextured": false },
    { "name": "[03] Waterless Stone", "isOriented": false, "isTextured": false },
    { "name": "[04] Win", "isOriented": false, "isTextured": false },
    { "name": "[05] Stair", "isOriented": true, "isTextured": false },
    { "name": "[06] Bin", "isOriented": false, "isTextured": false },
    { "name": "[07] Stone Wedge", "isOriented": true, "isTextured": false },
    { "name": "[08] Dirt Wedge", "isOriented": true, "isTextured": false },
    { "name": "[09] Yellow Ball", "isOriented": false, "isTextured": false },
    { "name": "[10] Fake Win", "isOriented": true, "isTextured": false },
    { "name": "[11] Water", "isOriented": false, "isTextured": false },
    { "name": "[12] Grass", "isOriented": false, "isTextured": false },
    { "name": "[13] Dark Pillar", "isOriented": false, "isTextured": false },
    { "name": "[14] Stone Rounded", "isOriented": true, "isTextured": false },
    { "name": "[15] Robot Tap To Walk (B)", "isOriented": true, "isTextured": false },
    { "name": "[16] Zapper", "isOriented": true, "isTextured": false },
    { "name": "[17] Draggable", "isOriented": false, "isTextured": false },
    { "name": "[18] Dirt From Grass", "isOriented": false, "isTextured": false },
    { "name": "[19] Wheel", "isOriented": true, "isTextured": false },
    { "name": "[20] Metal Stair", "isOriented": true, "isTextured": false },
    { "name": "[21] Metal Rounded", "isOriented": true, "isTextured": false },
    { "name": "[22] Motor", "isOriented": true, "isTextured": false },
    { "name": "[23] Engine Box", "isOriented": false, "isTextured": false },
    { "name": "[24] Stone", "isOriented": false, "isTextured": false },
    { "name": "[25] Metal", "isOriented": false, "isTextured": false },
    { "name": "[26] Robot Turns Right (R)", "isOriented": true, "isTextured": false },
    { "name": "[27] Eye", "isOriented": false, "isTextured": false },
    { "name": "[28] Hidden", "isOriented": false, "isTextured": false },
    { "name": "[29] Metal Stone With Orientation", "isOriented": true, "isTextured": false },
    { "name": "[30] Curve Rail", "isOriented": true, "isTextured": false },
    { "name": "[31] Metal Stone Pillar", "isOriented": true, "isTextured": false },
    { "name": "[32] Metal Half Pillar", "isOriented": true, "isTextured": false },
    { "name": "[33] Slider Rail", "isOriented": true, "isTextured": false },
    { "name": "[34] Stone Half Pillar", "isOriented": true, "isTextured": false },
    { "name": "[35] Stone Pillar", "isOriented": true, "isTextured": false },
    { "name": "[36] Draggable Pillar", "isOriented": true, "isTextured": false },
    { "name": "[37] Ball", "isOriented": false, "isTextured": false },
    { "name": "[38] Waterless Stone", "isOriented": false, "isTextured": false },
    { "name": "[39] Metal Pillar", "isOriented": true, "isTextured": false },
    { "name": "[40] Battery Box", "isOriented": false, "isTextured": false },
    { "name": "[41] Slider", "isOriented": true, "isTextured": false },
    { "name": "[42] Noisy Sound Box", "isOriented": false, "isTextured": false },
    { "name": "[43] Fence", "isOriented": true, "isTextured": false },
    { "name": "[44] Box (Undefined)", "isOriented": false, "isTextured": false },
    { "name": "[45] Theme Sound Box", "isOriented": false, "isTextured": false },
    { "name": "[46] Card Sound Box", "isOriented": false, "isTextured": false },
    { "name": "[47] Trigger", "isOriented": false, "isTextured": false },
    { "name": "[48] Box (Undefined)", "isOriented": false, "isTextured": false },
    { "name": "[49] Metal Wedge", "isOriented": true, "isTextured": false },
    { "name": "[50] Robot Turns Left (L)", "isOriented": true, "isTextured": false },
    { "name": "[51] Star", "isOriented": false, "isTextured": false },
    { "name": "[52] Dirt", "isOriented": false, "isTextured": false },
    { "name": "[53] Frame", "isOriented": false, "isTextured": false },
    { "name": "[54] Font OFF", "isOriented": false, "isTextured": true },
    { "name": "[55] Font ON", "isOriented": false, "isTextured": true },
    { "name": "[56] Font ON/OFF", "isOriented": false, "isTextured": true },
    { "name": "[57] Fake Motor (Stone-Brick)", "isOriented": true, "isTextured": true },
    { "name": "[58] Fake Motor (Grass-Fence)", "isOriented": true, "isTextured": true },
    { "name": "[59] Fake Motor (Dirt)", "isOriented": true, "isTextured": true },
    { "name": "[60] Fake Motor (Brick-Metal)", "isOriented": true, "isTextured": true },
    { "name": "[61] Wire", "isOriented": true, "isTextured": false },
    { "name": "[62] L Wire", "isOriented": true, "isTextured": false },
    { "name": "[63] T Wire", "isOriented": true, "isTextured": false },
    { "name": "[64] Font OFF", "isOriented": false, "isTextured": true },
    { "name": "[65] Fake Motor (R-L)", "isOriented": true, "isTextured": true },
    { "name": "[66] Font ON/OFF", "isOriented": false, "isTextured": true },
    { "name": "[67] Fake Motor (Zapper)", "isOriented": true, "isTextured": true }
];

export const orientations = [
	"Up-Forward", "Up-Right", "Up-Back", "Up-Left", 
	"Forward-Down", "Right-Down", "Back-Down", "Left-Down", 
	"Down-Back", "Down-Left", "Down-Forward", "Down-Right", 
	"Back-Up", "Left-Up", "Forward-Up", "Right-Up", 
	"Left-Forward", "Forward-Right", "Right-Back", "Back-Left", 
	"Right-Forward", "Back-Right", "Left-Back", "Forward-Left"
];

export const fontTexture = Array.from({ length: 256 }, (_, i) => i);

